const express = require("express");
const app = express();
const port = 3000;
let customers = [{ id: 1, name: "Andi", city: "Dortmund" }, { id: 2, name: "Sara", city: "Berlin" }];
let products = [{ id: 1, name: "Laptop", price: 999 }, { id: 2, name: "Mouse", price: 25 }];
app.get("/", function (request, response) { response.status(200).json({ message: "Welcome to my API" }); });
app.get("/customers", function (request, response) { response.status(200).json(customers); });
app.get("/products", function (request, response) { response.status(200).json(products); });
app.get("/customers/:id", function (request, response) { const id = Number(request.params.id); const customer = customers.find(function (item) { return item.id === id; }); if (!customer) { return response.status(404).json({ error: "Customer not found" }); } response.status(200).json(customer); });
app.use(function (request, response) { response.status(404).json({ error: "Route not found" }); });
app.listen(port, function () { console.log("Server is running on port " + port); });
