const express = require("express");
const app = express();
const port = 3000;
app.use(express.json());
let customers = [{ id: 1, name: "Andi", city: "Dortmund" }, { id: 2, name: "Sara", city: "Berlin" }];
let products = [{ id: 1, name: "Laptop", price: 999 }, { id: 2, name: "Mouse", price: 25 }];
app.get("/", function (request, response) { response.status(200).json({ message: "Welcome to my API" }); });
app.get("/customers", function (request, response) { response.status(200).json(customers); });
app.get("/products", function (request, response) { response.status(200).json(products); });
app.get("/customers/:id", function (request, response) { const id = Number(request.params.id); const customer = customers.find(function (item) { return item.id === id; }); if (!customer) { return response.status(404).json({ error: "Customer not found" }); } response.status(200).json(customer); });
app.post("/customers", function (request, response) { if (!request.body.name || !request.body.city) { return response.status(400).json({ error: "Customer name and city are required" }); } const newCustomer = { id: customers.length + 1, name: request.body.name, city: request.body.city }; customers.push(newCustomer); response.status(201).json(newCustomer); });
app.put("/customers/:id", function (request, response) { const id = Number(request.params.id); const index = customers.findIndex(function (item) { return item.id === id; }); if (index === -1) { return response.status(404).json({ error: "Customer not found" }); } customers[index] = { id: id, name: request.body.name, city: request.body.city }; response.status(200).json(customers[index]); });
app.delete("/customers/:id", function (request, response) { const id = Number(request.params.id); const index = customers.findIndex(function (item) { return item.id === id; }); if (index === -1) { return response.status(404).json({ error: "Customer not found" }); } customers.splice(index, 1); response.status(200).json({ message: "Customer deleted" }); });
app.post("/products", function (request, response) { const newProduct = { id: products.length + 1, name: request.body.name, price: request.body.price }; products.push(newProduct); response.status(201).json(newProduct); });
app.get("/products/:id", function (request, response) { const id = Number(request.params.id); const product = products.find(function (item) { return item.id === id; }); if (!product) { return response.status(404).json({ error: "Product not found" }); } response.status(200).json(product); });
app.put("/products/:id", function (request, response) { const id = Number(request.params.id); const index = products.findIndex(function (item) { return item.id === id; }); if (index === -1) { return response.status(404).json({ error: "Product not found" }); } products[index] = { id: id, name: request.body.name, price: request.body.price }; response.status(200).json(products[index]); });
app.delete("/products/:id", function (request, response) { const id = Number(request.params.id); const index = products.findIndex(function (item) { return item.id === id; }); if (index === -1) { return response.status(404).json({ error: "Product not found" }); } products.splice(index, 1); response.status(200).json({ message: "Product deleted" }); });
app.use(function (request, response) { response.status(404).json({ error: "Route not found" }); });
app.listen(port, function () { console.log("Server is running on port " + port); });
